# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, null=True)),
                ('year_of_passsing', models.DateField()),
                ('percentage', models.FloatField()),
                ('university_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Passbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_page', models.ImageField(null=True, upload_to='')),
                ('back_page', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Below_SSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_passsing', models.DateField()),
                ('percentage', models.FloatField()),
                ('state_board', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile1', models.CharField(max_length=15, null=True)),
                ('mobile2', models.CharField(max_length=15, null=True)),
                ('telephone1', models.CharField(max_length=15, null=True)),
                ('telephone2', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bachelors', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Bachelors')),
                ('below_ssc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Below_SSC')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('relation', models.CharField(max_length=100, null=True)),
                ('house_no', models.CharField(max_length=100, null=True)),
                ('street_no', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('at_po', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('google_pin', models.CharField(max_length=100, null=True)),
                ('contact_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Contact_Number')),
            ],
        ),
        migrations.CreateModel(
            name='General_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('physical_disability', models.CharField(max_length=100, null=True)),
                ('contact_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Contact_Number')),
                ('emergency_contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Emergency_Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ID_Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.ImageField(null=True, upload_to='')),
                ('election_card', models.ImageField(null=True, upload_to='')),
                ('pan_card', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_passsing', models.DateField()),
                ('percentage', models.FloatField()),
                ('state_board', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField(null=True)),
                ('to_year', models.IntegerField(null=True)),
                ('organisation', models.CharField(max_length=300, null=True)),
                ('total_years', models.IntegerField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('reason_left', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_experience', models.ManyToManyField(to='demo.JobExperience')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_page', models.ImageField(null=True, upload_to='')),
                ('back_page', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Permanent_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100, null=True)),
                ('street_no', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('at_po', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('google_pin', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PG_Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, null=True)),
                ('year_of_passsing', models.DateField()),
                ('percentage', models.FloatField()),
                ('university_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_passsing', models.DateField()),
                ('percentage', models.FloatField()),
                ('state_board', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100, null=True)),
                ('street_no', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('at_po', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('google_pin', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_degree', models.ImageField(null=True, upload_to='')),
                ('bachelors', models.ImageField(null=True, upload_to='')),
                ('intermediate', models.ImageField(null=True, upload_to='')),
                ('ssc', models.ImageField(null=True, upload_to='')),
                ('below_ssc', models.ImageField(null=True, upload_to='')),
                ('signature', models.ImageField(null=True, upload_to='')),
                ('thumb_impression', models.ImageField(null=True, upload_to='')),
                ('passport_size', models.ImageField(null=True, upload_to='')),
                ('full_body', models.ImageField(null=True, upload_to='')),
                ('medical', models.ImageField(null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='')),
                ('bank_passbook', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Bank_Passbook')),
                ('passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_page', models.ImageField(null=True, upload_to='')),
                ('back_page', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='uploads',
            name='visa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Visa'),
        ),
        migrations.AddField(
            model_name='general_profile',
            name='id_proof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.ID_Proof'),
        ),
        migrations.AddField(
            model_name='general_profile',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Name'),
        ),
        migrations.AddField(
            model_name='general_profile',
            name='permanent_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Permanent_Address'),
        ),
        migrations.AddField(
            model_name='general_profile',
            name='temporary_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Temporary_Address'),
        ),
        migrations.AddField(
            model_name='educational_profile',
            name='pg_degeree',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.PG_Degree'),
        ),
        migrations.AddField(
            model_name='educational_profile',
            name='ssc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.SSC'),
        ),
    ]
