# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20171020_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_proof',
            name='aadhar_card',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='id_proof',
            name='election_card',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='id_proof',
            name='pan_card',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='from_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='to_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
