# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20171020_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelors',
            name='year_of_passsing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='below_ssc',
            name='year_of_passsing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='year_of_passsing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pg_degree',
            name='year_of_passsing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='year_of_passsing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
