# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20171020_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='below_ssc',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_details',
            name='current_salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_details',
            name='expected_salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
