# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20171020_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelors',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pg_degree',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
