# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20171020_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_profile',
            name='intermediate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Intermediate'),
        ),
    ]
