# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_educational_profile_intermediate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educational_profile',
            old_name='pg_degeree',
            new_name='pg_degree',
        ),
    ]
