# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20171021_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='values',
        ),
        migrations.AddField(
            model_name='skills',
            name='values',
            field=models.ManyToManyField(null=True, to='demo.Skill'),
        ),
    ]
