# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20171021_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bachelors',
            old_name='year_of_passsing',
            new_name='year_of_passing',
        ),
        migrations.RenameField(
            model_name='below_ssc',
            old_name='year_of_passsing',
            new_name='year_of_passing',
        ),
        migrations.RenameField(
            model_name='intermediate',
            old_name='year_of_passsing',
            new_name='year_of_passing',
        ),
        migrations.RenameField(
            model_name='pg_degree',
            old_name='year_of_passsing',
            new_name='year_of_passing',
        ),
        migrations.RenameField(
            model_name='ssc',
            old_name='year_of_passsing',
            new_name='year_of_passing',
        ),
    ]
