# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0012_maid_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('passport_size', models.ImageField(upload_to='admin/')),
                ('contact_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Contact_Number')),
                ('id_proof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.ID_Proof')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Name')),
                ('permanent_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Permanent_Address')),
                ('temporary_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Temporary_Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('passport_size', models.ImageField(upload_to='agent/')),
                ('contact_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Contact_Number')),
                ('id_proof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.ID_Proof')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Name')),
                ('permanent_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Permanent_Address')),
                ('temporary_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Temporary_Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
