# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=100),
        ),
    ]
